### PR TITLE
Added platform list description for mobile

### LINKED ISSUE #31: Add a heading for platform list
Tell people they can listen on any of those platforms.

### PR DESCRIPTION
**Pull request by CatChen**
This should resolve #31. This should help #33. cc @siying

Screenshot 2020-03-24 19 28 41

### CODE REVIEW

**Comment by siying** [comment]
Awesome!

**Comment by siying** [comment]
How about add a Castro link too? e.g. https://castro.fm/podcast/a4d36daa-8216-482d-8935-d156f42b8fbd

**Comment by CatChen** [comment]
@siying I'll need to find an icon of the same style for Castro and Ximalaya.

**Comment by siying** [comment]
> @siying I'll need to find an icon of the same style for Castro and Ximalaya.

and youtube? :)

**Comment by siying** [comment]
and Bilibili potentially:p

**Pull request merged**
